version: '3.8'
services:

  discoveryserver:
    build: 
      context: .
      dockerfile: discoverserver/Dockerfile
    ports:
      - "8761:8761"
    networks:
      - microservice-networks


  apigateway:
    build: 
      context: .
      dockerfile: apigateway/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - microservice-networks
    depends_on:
      - discoveryserver
      - redis


  bookservice:
    build: 
      context: .
      dockerfile: bookservice/Dockerfile
    ports:
      - "9001:9001"
    networks:
      - microservice-networks
    depends_on:
      - discoveryserver
      - axonserver
    environment:
      - "AXONIQ_AXONSERVER_SERVERS=axonserver:8024"


  axonserver:
    image: axoniq/axonserver:latest
    hostname: axonserver
    container_name: axonserver
    ports:
      - "8024:8024"
      - "8124:8124"
      - "8224:8224"
    environment:
      AXONIQ_AXONSERVER_STANDALONE: "true" # Set to true for standalone mode
      AXONIQ_AXONSERVER_HOSTNAME: "axonserver" # Ensures clients can connect
    # volumes:
    #   - ./data:/data
    #   - ./events:/events
    #   - ./config:/config
    networks:
      - microservice-networks

  redis:
    image: redis:latest
    restart: always
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      - microservice-networks


networks:
  microservice-networks:
    driver: bridge
