server:
  port: 8080 # Gateway port

spring:
  application:
    name: apigateway
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    gateway:
      discover:
        locator:
          enabled: true
      routes:
        - id: employeeservice
          uri: lb://employeeservice
          predicates:
            - Path=/api/v1/employees/** # Matches requests starting with /api/v1/employees
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                redis-rate-limiter.requestedTokens: 1 # Cost of each request, defaults to 1
            - KeyAuthFilter
        - id: bookservice
          uri: lb://bookservice
          predicates:
            - Path=/api/v1/books/** # Matches requests starting with /api/v1/employees
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                redis-rate-limiter.requestedTokens: 1 # Cost of each request, defaults to 1
            - KeyAuthFilter
eureka:
  instance:
    hostname: discoveryserver # Explicitly sets the hostname to localhost
  client:
    register-with-eureka: true # The gateway registers itself with the Eureka server
    fetch-registry: true # The gateway fetches the registry from the Eureka server
    service-url:
      defaultZone: ${EUREKA_URI:http://discoveryserver:8761/eureka} # Eureka server address

apiKey: ltfullstack